collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5342553285881877
  brandStrength: 0.01532306266017258
  lightness: 0.4644826925359666
  brandColors:
    - '#0E0E10'
    - '#F9EFD2'
    - '#D0C495'
    - '#6E675F'
    - '#878F8A'
  rhythmicContrast: 0.4880134279374033
typography_spectrum: 0
layout_spectrum: 0.3512545
name: Abhinav Anguria
